# Generated by Django 5.1.1 on 2024-12-17 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('error', models.CharField(max_length=255)),
                ('webhook_version', models.CharField(choices=[(1, 'V1'), (2, 'V2')], max_length=50)),
                ('level', models.CharField(choices=[(1, 'info'), (2, 'warn'), (3, 'error'), (4, 'fatal')], max_length=50)),
                ('action', models.CharField(choices=[(1, 'failed'), (2, 'successful')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
