# Generated by Django 5.1.1 on 2024-11-06 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('webhook_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('webhook_name', models.CharField(max_length=255)),
                ('webhook_url', models.CharField(max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.webhook')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('custom_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_id', models.CharField(max_length=255)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.webhook')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('contact_tag_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_id', models.CharField(max_length=255)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.webhook')),
            ],
        ),
    ]
