# Generated by Django 5.1.1 on 2024-11-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_integrate', '0002_webhook_is_filter_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.webhook')),
            ],
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
