# Generated by Django 5.1.1 on 2024-11-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_integrate', '0002_webhook_is_filter_user_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='FilterKeys',
        ),
    ]
