# Generated by Django 5.1.1 on 2024-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_integrate', '0002_requestdata_shop_webhook_webhookaction_webhookfilter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookaction',
            name='creation_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookaction',
            name='total_cost',
            field=models.CharField(blank=True, null=True),
        ),
    ]
