# Generated by Django 5.1.1 on 2024-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_integrate', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
