# Generated by Django 5.1.1 on 2024-12-17 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_integrate', '0005_alter_customer_customer_id_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_data', models.JSONField()),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_integrate.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
